# Generated by Django 3.2.9 on 2021-12-28 03:15

from django.db import migrations
import random
def default_data_for_category(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("blog", "Category")
    SubCat = apps.get_model("blog", "SubCategory")
    Contents = apps.get_model("blog", "Content")
    data = [
        {"name": "Default"},
        {"name": "Daily",},
        {"name": "Tech",},
    ]

    for d in data:
        c = Category(**d)
        c.save()

    all_cat = Category.objects.all() 
    for cat in all_cat:
        for i in range(1, random.randint(2, 5)):
            sc = SubCat(name=f"Sub Category {cat.name} - {i}", category=cat)
            sc.save()
    all_sub = SubCat.objects.all() 

    for sub in all_sub:
        for i in range(1, random.randint(2, 7)):
            cont = Contents(title=f"Title for {sub.name}- {i}", category=sub.category, sub_category=sub)
            cont.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [migrations.RunPython(default_data_for_category)]
